<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Cortex.Metrics</RootNamespace>
    <AssemblyName>Cortex.Metrics</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.11.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Cortex.Core\Cortex.Core.csproj" />
    <ProjectReference Include="..\Cortex.Roslyn\Cortex.Roslyn.csproj" />
  </ItemGroup>
</Project>
