<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Cortex.Git</RootNamespace>
    <AssemblyName>Cortex.Git</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="LibGit2Sharp" Version="0.31.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Cortex.Core\Cortex.Core.csproj" />
    <ProjectReference Include="..\Cortex.Graph\Cortex.Graph.csproj" />
  </ItemGroup>
</Project>
